# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://nstaging.daouoffice.com/login")
    self.driver.set_window_size(1552, 840)
    # self.driver.find_element(By.ID, "username").click()
    # self.driver.find_element(By.ID, "username").send_keys("yoojin1216")
    # self.driver.find_element(By.ID, "password").send_keys("1qaz2wsx#")
    # self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    # self.driver.find_element(By.LINK_TEXT, "게시판").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".board-tree-nodes:nth-child(2) .txt").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".custom_header .btn_tool:nth-child(1) > .txt").click()
    # self.driver.find_element(By.ID, "dropZone").click()
    # self.driver.find_element(By.ID, "subject").click()
    # self.driver.find_element(By.ID, "subject").send_keys("자동화")
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.LINK_TEXT, "HTML").click()
    element = self.driver.find_element(By.LINK_TEXT, "HTML")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "dext5_source_editor").click()
    self.driver.find_element(By.LINK_TEXT, "디자인").click()
    self.driver.find_element(By.ID, "dext5_source_editor").send_keys("<p><br></p>자동화자동화")
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".btn_major").click()
  
