# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
    def test_newTest(self):
      self.driver.get("https://nstaging.daouoffice.com/login")
      self.driver.set_window_size(829, 694)
      self.driver.find_element(By.ID, "password").send_keys("1q2w3e4r!")
      self.driver.find_element(By.CSS_SELECTOR, ".login_box:nth-child(1)").click()
      self.driver.find_element(By.ID, "password").send_keys("1q2w3e4r@")
      self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
      self.driver.find_element(By.ID, "password").send_keys("1q2w3e4r!")
      self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
      element = self.driver.find_element(By.LINK_TEXT, "게시판")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(17) .menu").click()
      self.driver.switch_to.frame(0)
      self.driver.find_element(By.CSS_SELECTOR, ".primary-icon").click()
      self.driver.find_element(By.CSS_SELECTOR, ".primary-icon").click()
      element = self.driver.find_element(By.CSS_SELECTOR, ".item-2depth > .v-list-item__title")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      self.driver.find_element(By.CSS_SELECTOR, ".item-2depth > .v-list-item__title").click()
      element = self.driver.find_element(By.CSS_SELECTOR, "body")
      actions = ActionChains(self.driver)
      actions.move_to_element(element, 0, 0).perform()
      # for i in range(0, 5):  # try .. except 사이의 코드 실행 중 exception 발생하면 5번 반복합니다.
      #   try:
      #       # 실행해야 하는 코드
      #       break
      #   except Exception as e:
      #       print(f"Exception [{e}] - Retrying")
      #       time.sleep(2)