# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEx1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  def test_ex1(self):
    self.driver.get("https://portal.daou.co.kr/login")
    self.driver.set_window_size(1011, 840)
    self.driver.find_element(By.ID, "username").send_keys("yoojin1216")
    self.driver.find_element(By.ID, "password").send_keys("suji10815!")
    self.driver.find_element(By.CSS_SELECTOR, ".login_box:nth-child(1)").click()
    self.driver.find_element(By.ID, "login_submit").click()
    element = self.driver.find_element(By.ID, "login_submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.close()


# driver = webdriver.Chrome()
# driver.get("https://portal.daou.co.kr")
# try:
#     element = WebDriverWait(driver, 10).until(
#       EC.presence_of_element_located((By.ID, "username")),
#       EC.presence_of_element_located((By.ID, "password")),
#       EC.presence_of_element_located((By.ID, "login_submit")),
#       EC.presence_of_element_located((By.CSS_SELECTOR, 'body')),
#       EC.presence_of_element_located((By.CSS_SELECTOR, '.login_box'))
#     )
# finally:
#     driver.quit()