# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://nstaging.daouoffice.com/app/att_timeline")
    self.driver.set_window_size(1552, 840)
    self.driver.switch_to.default_content()
    self.driver.find_element(By.CSS_SELECTOR, ".on .menu").click()
    self.driver.switch_to.frame(0)
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(1) .v-btn__content").click()
    self.driver.execute_script("window.scrollTo(0,122.39999389648438)")
    self.driver.find_element(By.CSS_SELECTOR, ".ma-0:nth-child(7)").click()
    self.driver.find_element(By.ID, "input-84").click()
    self.driver.find_element(By.CSS_SELECTOR, "#list-item-144-8 .v-list-item__title").click()
    self.driver.find_element(By.ID, "input-93").click()
    self.driver.find_element(By.CSS_SELECTOR, "#list-item-168-1 .v-list-item__title").click()
    self.driver.find_element(By.ID, "input-96").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".v-btn--has-bg > .v-btn__content")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "input-96").send_keys("출근입니다")
    self.driver.find_element(By.CSS_SELECTOR, ".v-btn--has-bg > .v-btn__content").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
